version: '3.9'

services:
  market_db:
    container_name: 'market_db'
    image: 'postgres:13'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: hackme
      POSTGRES_DB: market_db
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data