version: '3.9'

services:
  market_app:
    build: .
    depends_on:
      - market_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: hackme
      POSTGRES_DB: market_db
      POSTGRES_HOST: market_db
      POSTGRES_PORT: 5432
    ports:
      - "80:80"

  market_db:
    container_name: 'market_db'
    image: 'postgres:13'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: hackme
      POSTGRES_DB: market_db
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
