"""empty message

Revision ID: 58307d4da0df
Revises: 
Create Date: 2022-11-17 12:55:23.297919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58307d4da0df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
