"""empty message

Revision ID: 944778bc5ad6
Revises: 
Create Date: 2022-11-21 02:25:58.792244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '944778bc5ad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_title'), 'categories', ['title'], unique=True)
    op.create_table('items',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=True)
    op.create_table('items_categories',
    sa.Column('item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'category_id')
    )
    op.create_index(op.f('ix_items_categories_category_id'), 'items_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_categories_item_id'), 'items_categories', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_categories_item_id'), table_name='items_categories')
    op.drop_index(op.f('ix_items_categories_category_id'), table_name='items_categories')
    op.drop_table('items_categories')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_categories_title'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
